version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  php:
    image: php:7-fpm
    volumes:
      - ./web:/var/www

  web:
    depends_on:
      - db
      - php
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www
      - ./cicd/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}
